
[env:format_esp32s3-diy]
extends = esp32s3_base
board = esp32-s3-devkitc-1
board_level = extra
;board_upload.flash_size = 16MB ;Specify the FLASH capacity as 16MB
board_build.flash_mode = qio               ; Flash模式：QIO
board_build.psram_type = opi               ; PSRAM类型：OPI（8MB PSRAM对应OPI模式）

; Flash容量配置
board_upload.flash_size = 16MB             ; Flash总容量16MB
board_upload.maximum_size = 16777216       ; 16MB对应的字节数（16*1024*1024）
board_build.partitions = default_16MB.csv  ; 16MB Flash对应的分区表

build_unflags =
  ${esp32s3_base.build_unflags}
  -DARDUINO_USB_MODE=1
build_flags =
  ${esp32s3_base.build_flags}
  -D EBYTE_ESP32_S3
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=0
  ;-D OLED_CN
  -I variants/esp32s3/diy/format_esp32s3-diy
; 启用PSRAM编译宏
board_build.extra_flags = -DBOARD_HAS_PSRAM
upload_speed = 921600